const CourseData = [
  {
    coursename: "Introduction to Full Stack Development",
    Instructor: "Alice Johnson",
    rating: "4.6",
    ratednumber: "320",
    lectures: 18,
    duration: "12.00 Hrs",
    skillLevel: "Beginner",
    language: "English",
    price: "$149",
    bgImg: "https://themewagon.github.io/Edukate/img/courses-1.jpg",
  },
  {
    coursename: "Mastering Frontend with React & Redux",
    Instructor: "Brian Thompson",
    rating: "4.7",
    ratednumber: "540",
    lectures: 22,
    duration: "14.30 Hrs",
    skillLevel: "Intermediate",
    language: "English",
    price: "$179",
    bgImg: "https://themewagon.github.io/Edukate/img/courses-2.jpg",
  },
  {
    coursename: "Backend Development with Node.js & Express",
    Instructor: "Cynthia Lee",
    rating: "4.5",
    ratednumber: "410",
    lectures: 19,
    duration: "13.00 Hrs",
    skillLevel: "Intermediate",
    language: "English",
    price: "$189",
    bgImg: "https://themewagon.github.io/Edukate/img/courses-3.jpg",
  },
  {
    coursename: "UI/UX Design Principles for Web",
    Instructor: "Daniel Wright",
    rating: "4.8",
    ratednumber: "280",
    lectures: 16,
    duration: "9.50 Hrs",
    skillLevel: "All Level",
    language: "English",
    price: "$139",
    bgImg: "https://themewagon.github.io/Edukate/img/courses-4.jpg",
  },
  {
    coursename: "JavaScript Essentials for Beginners",
    Instructor: "Emma Davis",
    rating: "4.4",
    ratednumber: "620",
    lectures: 20,
    duration: "11.00 Hrs",
    skillLevel: "Beginner",
    language: "English",
    price: "$129",
    bgImg: "https://themewagon.github.io/Edukate/img/courses-5.jpg",
  },
  {
    coursename: "Building APIs with Python & Django",
    Instructor: "Franklin Moore",
    rating: "4.6",
    ratednumber: "350",
    lectures: 17,
    duration: "10.45 Hrs",
    skillLevel: "Intermediate",
    language: "English",
    price: "$159",
    bgImg: "https://themewagon.github.io/Edukate/img/courses-6.jpg",
  },
];

const courseDataWithIds = CourseData.map((course, index) => ({
  id: `course-${index + 1}`,
  ...course,
}));

export default courseDataWithIds;
